cookbook "apt", :git => "https://github.com/opscode-cookbooks/apt.git"
cookbook "mysql", :git => "https://github.com/opscode-cookbooks/mysql.git"
cookbook "java", :git => "https://github.com/opscode-cookbooks/java.git"
cookbook "jetty", :git => "https://github.com/opscode-cookbooks/jetty.git"
cookbook "haproxy", :git => "https://github.com/coroutine/chef-haproxy.git"